name: mise project setup
description: Setup mise and tools for project
inputs:
  cache-mode:
    description: "Mode of operation regarding cache: 'prepare' or 'use'"
    required: false
    default: use

runs:
  using: composite
  steps:
    - id: init

      env:
        CACHE_MODE: ${{ inputs.cache-mode }}
        # renovate: datasource=github-releases depName=jdx/mise
        MISE_VERSION: v2025.12.5
      run: |
        # Initialize mise-project-setup action
        "${GITHUB_ACTION_PATH}/init.sh"
      shell: bash

    - name: Install mise
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      with:
        cache_save: ${{ inputs.cache-mode == 'prepare' }}
        version: ${{ steps.init.outputs.mise-version }}

    - run: |
        # Ensure tools are installed properly
        mise ls --current
        count=$(mise ls --current --missing --no-header | wc -l)
        if [ $count -gt 0 ]; then
          echo "::error::Count of missing tools: $count"
          exit 1
        else
          echo "Result of check: no missing tools"
        fi
      shell: bash
