name: Check - prettier
on:
  pull_request:
    paths-ignore:
      # These need to match rules in .prettierignore
      - "src/*/README.md"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@b216e1ae8983e72a3195846d15ae28b5f35f1083
