name: Check - GitHub actions
on:
  pull_request:
    paths:
      - ".github/workflows/**.yaml"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
