name: Check - Devcontainer
on:
  pull_request:
    paths:
      - ".devcontainer/**"
      - ".github/workflows/check-devcontainer.yaml"
      - "package.json"
      - "yarn.lock"
      - "src/**"
      - "!src/**/README.md"
      - "!src/**/NOTES.md"
      - "test/**"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-devcontainer.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
    with:
      runCmd: |
        for feature in $(ls src); do
          echo "Checking $feature"
          yarn exec devcontainer features test -f "$feature" -i "mcr.microsoft.com/devcontainers/base:debian" .
        done
