name: "CI - Checks"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check format
        run: npm run format

  renovate-config-validator:
    name: "Renovate config validator"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.0
