name: Check - Renovate config
on:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/check-renovate-config.yaml"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
