name: "CI - Checks"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: "Check format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Taskfile
        uses: Illbjorn/setup-task@0.1.0

      - name: Check format
        run: task format
