name: Check - Renovate config
on:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/check-renovate-config.yaml"
  workflow_dispatch:

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@18e084501edc3ba04f03f3dd40d7288765100e52
