name: Check - GitHub actions
on:
  pull_request:
    paths:
      - ".github/workflows/**.yaml"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@d1a61f55379d78d23d5216a80591dfe37384942d
