name: Check - Format
on:
  pull_request:
    paths-ignore:
      # These need to match rules in .prettierignore
      - "src/*/README.md"
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:

jobs:
  format:
    name: Validate formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/npm-project-setup
      - name: Check format
        run: npm run check:prettier
