name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  mise-cache:
    uses: nikobockerman/github-workflows/.github/workflows/mise-prepare-cache.yaml@6b7289db4c7f50220e2ae3c11e9d117f572b5010 # v1.0.11
  check-feature-configs:
    uses: ./.github/workflows/check-feature-configs.yaml
  check-prettier:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@6b7289db4c7f50220e2ae3c11e9d117f572b5010 # v1.0.11
    with:
      task: check:prettier
  check-renovate-config:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@6b7289db4c7f50220e2ae3c11e9d117f572b5010 # v1.0.11
    with:
      task: check:renovateconfig
  check-shellcheck:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@6b7289db4c7f50220e2ae3c11e9d117f572b5010 # v1.0.11
    with:
      task: check:shellcheck
  test-features:
    needs: mise-cache
    uses: ./.github/workflows/test-features.yaml

  check:
    needs:
      - check-feature-configs
      - check-prettier
      - check-renovate-config
      - check-shellcheck
      - test-features
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
