name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  mise-cache:
    uses: ./.github/workflows/mise-prepare-cache.yaml

  check-feature-configs:
    uses: ./.github/workflows/check-feature-configs.yaml

  check-prettier:
    needs: mise-cache
    uses: ./.github/workflows/mise-task.yaml
    with:
      task: check:prettier

  check-shellcheck:
    needs: mise-cache
    uses: ./.github/workflows/mise-task.yaml
    with:
      task: check:shellcheck

  test-features:
    needs: mise-cache
    uses: ./.github/workflows/test-features.yaml

  check:
    if: always()
    needs:
      - check-feature-configs
      - check-prettier
      - check-shellcheck
      - test-features
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
