name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  check-feature-configs:
    uses: ./.github/workflows/check-feature-configs.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@1d0ee1b00422598a785e5620925ce2ec0de2b6d3
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@1d0ee1b00422598a785e5620925ce2ec0de2b6d3
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@1d0ee1b00422598a785e5620925ce2ec0de2b6d3
  check-shellcheck:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@1d0ee1b00422598a785e5620925ce2ec0de2b6d3
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@1d0ee1b00422598a785e5620925ce2ec0de2b6d3
  test-features:
    uses: ./.github/workflows/test-features.yaml

  prebuild-devcontainer:
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@1d0ee1b00422598a785e5620925ce2ec0de2b6d3
    permissions:
      contents: read
      packages: write
    with:
      cache-type: intermediate
  check-devcontainer:
    needs: prebuild-devcontainer
    uses: ./.github/workflows/check-devcontainer.yaml
