name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  check-feature-configs:
    uses: ./.github/workflows/check-feature-configs.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  check-shellcheck:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  test-features:
    uses: ./.github/workflows/test-features.yaml
