name: CI
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  check-feature-configs:
    uses: ./.github/workflows/check-feature-configs.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@4f72abc1d57a1a8c8d2741d5b2dc84861eddb0cf
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@4f72abc1d57a1a8c8d2741d5b2dc84861eddb0cf
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@4f72abc1d57a1a8c8d2741d5b2dc84861eddb0cf
  check-shellcheck:
    uses: ./.github/workflows/check-shellcheck.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@4f72abc1d57a1a8c8d2741d5b2dc84861eddb0cf
  test-features:
    uses: ./.github/workflows/test-features.yaml
